### ISSUE TITLE
Error with Vue3

### ISSUE THREAD

**Issue by tedik123** [jscharting/jscharting-vue#25]
I copied and pasted the example in the vue3 documentation and I keep getting:
Uncaught SyntaxError: The requested module '/node_modules/jscharting/dist/jscharting.js?v=c78523e5' does not provide an export named 'Chart' (at jscharting.vue:6:10)

```
<template>
    <JSCharting :options="chartOptions" ></JSCharting>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue'
import JSCharting, { JSC } from 'jscharting-vue';

export default defineComponent({
   name: 'columnChart',
   setup() {
      const chartOptions = reactive({
         type: 'horizontal column',
         series: [
            {
               points: [
                  { x: 'A', y: 50 },
                  { x: 'B', y: 30 },
                  { x: 'C', y: 50 }
                  ]
              }
          ]
        } as JSC.JSCChartConfig);
      return { chartOptions }; 
    },
    components: {
        JSCharting
    }
});
</script>
```

**Comment by lllianreg** [comment]
+1

**Comment by lllianreg** [comment]
+1  vite下的

**Comment by n-osennij** [comment]
`Uncaught SyntaxError: The requested module '/node_modules/jscharting/dist/jscharting.js?v=296b01d1' does not provide an export named 'Chart' (at jscharting.vue:6:10)`

**Comment by iamcarlos94** [comment]
`Uncaught SyntaxError: ambiguous indirect export: Chart [jscharting.vue:2:10](http://0.0.0.0:5173/node_modules/jscharting-vue/src/components/jscharting.vue)`

**Comment by kirillshatalkin** [comment]
Changing vite config fixed issue
```
export default defineConfig({
    // ...
    optimizeDeps: {
        include: ['jscharting'],
    },
})

```
