### ISSUE TITLE
Error loading resources locally: Unexpected token '<'

### ISSUE THREAD

**Issue by lhardie** [jscharting/jscharting-vue#27]
I used npm to install jscharting-vue and it was working perfectly.  Then I edited my webpack config so that the resouces would be copied to a local folder to avoid using a CDN, as per the documentation.

However, now when I load a page with charts I get this error:
Uncaught SyntaxError: Unexpected token '<'
    at pw (jscharting.js:84:1)
    at success (jscharting.js:83:1)
    at b.onreadystatechange (jscharting.js:85:1)

I have not changed anything other than using webpack to copy the resources to a local folder (I have confirmed they are indeed copied), and added the baseUrl to my main.js.

If anyone has any hints or ideas, please do let me know.

**Comment by lhardie** [comment]
Apparently I had the wrong path as the baseUrl in my main.js.  The error message had me going in a different direction initially.
